# SPDX-License-Identifier: GPL-2.0
CFLAGS += -I../../../../include/uapi/
CFLAGS += -I../../../../include/
CFLAGS += -I../../../../usr/include/

TEST_GEN_PROGS := process_vm_exec ptrace_vm_exec

include ../lib.mk
